export const SCREEN = {
    SPLASH: 'SPLASH',
    LOGIN: 'LOGIN',
    TABS: 'TABS',
    DASHBOARD: 'DASHBOARD',
    CART: 'CART',
    SIGNUP: 'SIGNUP',
    //stacks
    STORESTACKSCREEN: 'STORESTACKSCREEN',
    ACCOUNTSTACKSCREEN: 'ACCOUNTSTACKSCREEN',
    //stacks
    ADDTOCART: 'ADDTOCART',
    STORES: 'STORES',
    STOREDETAIL: 'STOREDETAIL',
    //account
    PROFILE: 'PROFILE',
    ACCOUNT: 'ACCOUNT',
    ORDERS: 'ORDERS',
    ADDRESS: 'ADDRESS',
    PAYMENT: 'PAYMENT'
}